insert into public.academic_event_week (id, weekday, department, schedule_id, track_id)
values  (1, 'Monday', 'Computer Engineering', 297, 2),
        (2, 'Monday', 'Computer Engineering', 298, 2),
        (3, 'Tuesday', 'Computer Engineering', 299, 2),
        (4, 'Tuesday', 'Computer Engineering', 300, 2),
        (5, 'Tuesday', 'Computer Engineering', 301, 2),
        (6, 'Tuesday', 'Computer Engineering', 302, 2),
        (7, 'Tuesday', 'Computer Engineering', 303, 2),
        (8, 'Tuesday', 'Computer Engineering', 304, 2),
        (9, 'Tuesday', 'Computer Engineering', 316, 2),
        (10, 'Tuesday', 'Computer Engineering', 306, 2),
        (11, 'Wednesday', 'Computer Engineering', 305, 2),
        (12, 'Wednesday', 'Computer Engineering', 306, 2),
        (13, 'Wednesday', 'Computer Engineering', 307, 2),
        (14, 'Wednesday', 'Computer Engineering', 304, 2),
        (15, 'Wednesday', 'Computer Engineering', 309, 2),
        (16, 'Wednesday', 'Computer Engineering', 310, 2),
        (17, 'Wednesday', 'Computer Engineering', 311, 2),
        (18, 'Thursday', 'Computer Engineering', 312, 2),
        (19, 'Thursday', 'Computer Engineering', 313, 2),
        (20, 'Thursday', 'Computer Engineering', 314, 2),
        (21, 'Thursday', 'Computer Engineering', 315, 2),
        (51, 'Monday', 'Computer Engineering', 363, 2),
        (52, 'Monday', 'Computer Engineering', 364, 2),
        (53, 'Monday', 'Computer Engineering', 349, 2),
        (54, 'Tuesday', 'Computer Engineering', 350, 2),
        (55, 'Tuesday', 'Computer Engineering', 351, 2),
        (56, 'Tuesday', 'Computer Engineering', 352, 2),
        (57, 'Tuesday', 'Computer Engineering', 353, 2),
        (58, 'Tuesday', 'Computer Engineering', 354, 2),
        (59, 'Tuesday', 'Computer Engineering', 355, 2),
        (60, 'Tuesday', 'Computer Engineering', 356, 2),
        (61, 'Tuesday', 'Computer Engineering', 348, 2),
        (62, 'Wedneesday', 'Computer Engineering', 358, 2),
        (63, 'Wedneesday', 'Computer Engineering', 359, 2),
        (64, 'Wedneesday', 'Computer Engineering', 360, 2),
        (65, 'Wedneesday', 'Computer Engineering', 361, 2),
        (66, 'Wedneesday', 'Computer Engineering', 363, 2),
        (67, 'Wedneesday', 'Computer Engineering', 364, 2),
        (68, 'Thursday ', 'Computer Engineering', 365, 2),
        (69, 'Thursday ', 'Computer Engineering', 366, 2),
        (70, 'Thursday ', 'Computer Engineering', 362, 2),
        (71, 'Thursday ', 'Computer Engineering', 367, 2),
        (72, 'Thursday ', 'Computer Engineering', 368, 2),
        (73, 'Friday', 'Computer Engineering', 369, 2),
        (74, 'Friday', 'Computer Engineering', 370, 2);