insert into public.ratings (id, comments, building_id, classroom_id, office_id, lab_id, rate_value)
values  (5, 'This place stinks!', null, 1, null, null, 1),
        (6, 'Horrible place', null, 2, null, null, 2),
        (7, 'This place stinks!', null, 12, null, null, 1),
        (8, 'The room sometimes smells and the projector is too high up', null, 27, null, null, 2),
        (9, 'No wifi connectivity', null, 28, null, null, 3),
        (10, 'Some seats are broken', null, 3, null, null, 3),
        (11, 'Sound and projector system sometimes problematic, especially the projector. Causing lecturers to come along with their own projector', null, 6, null, null, 3),
        (12, 'I really like the place but the room but the AC is sometimes too low and the projection is always a problem', null, 19, null, null, 4),
        (13, 'Needs massive renovation, all the seats are destroyed', null, 24, null, null, 1),
        (14, 'AC is not usually turned on, which makes the auditorium very hot. Also, projection is an issue.', null, 24, null, null, 3),
        (15, 'The auditorium is being refurbished nicely', null, 24, null, null, 4),
        (16, 'Room is too small, and there is no cooling system.', null, 25, null, null, 3),
        (17, 'chairs and tables in the class are never organized', null, 11, null, null, 2),
        (18, 'Good sound and projection', null, 1, null, null, 4),
        (19, 'Good screen and projection', null, 1, null, null, 4),
        (20, 'Good sound and projection but room is often dirty', null, 2, null, null, 3),
        (21, 'The seats need to be fixed because we are forced to stand in the class', null, 4, null, null, 3),
        (22, 'The projectors keep going on and off, it must be checked', null, 14, null, null, 2);